#!/bin/sh -ue
#
# Script to setup environment (toolchain, SDK, etc)
#
# Sources:
#  - https://docs.espressif.com/projects/esp8266-rtos-sdk/en/release-v3.3/get-started/index.html
#  - https://docs.espressif.com/projects/esp8266-rtos-sdk/en/latest/get-started/linux-setup.html

DEPENDENCIES="gcc git wget make libncurses-dev flex bison gperf virtualenv"

if [ ! -d $(pwd)/xtensa-lx106-elf ] ; then
	echo "Downloading toolchain..."
	wget https://dl.espressif.com/dl/xtensa-lx106-elf-linux64-1.22.0-100-ge567ec7-5.2.0.tar.gz
	echo "Extracting toolchain..."
	tar xf xtensa-lx106-elf-linux64-1.22.0-100-ge567ec7-5.2.0.tar.gz
fi

if [ ! -d $(pwd)/ESP8266_RTOS_SDK ] ; then
	echo "Cloning SDK..."
	git clone --branch release/v3.3 --recursive https://github.com/espressif/ESP8266_RTOS_SDK.git
	export IDF_PATH=$(pwd)/ESP8266_RTOS_SDK
fi

for DEP in $DEPENDENCIES ; do
	if [ ! -e .stamp_installed_$DEP ] ; then
		echo "Installing dependency $DEP..."
		sudo apt-get -y install $DEP
		touch .stamp_installed_$DEP
	fi
done

if [ ! -d $(pwd)/pyEnv ] ; then
	echo "Creating python2.7 virtual environment..."
	virtualenv $(pwd)/pyEnv -p python2.7
	. $(pwd)/pyEnv/bin/activate

	# choose the correct python (not the system python)
	export PATH=$(pwd)/pyEnv/bin:$PATH

	echo "Installing python dependencies..."
	# pip install -r ESP8266_RTOS_SDK/docs/requirements.txt
	python -m pip install -r $IDF_PATH/requirements.txt
	python -m pip install pkg_resources pyserial

	deactivate
fi

if ! groups | grep -q dialout ; then
	echo "Adding user $USER to group dialout..."
	sudo usermod -a -G dialout $USER
	echo "Making changes to groups active..."
	sudo su $USER
fi

if [ ! -e setup_env ] ; then
	echo "Creating setup file..."
	cat <<EOF >>setup_env
#!/to/be/sourced!
#
# This shell script sets the environment variables. It is intended to be sourced.
#
# Do not edit this file. It was automatically created by $0 ($(date '+%y/%m/%d %H:%M'))
#
export PATH=\$PATH:$(pwd)/xtensa-lx106-elf/bin
export IDF_PATH=$(pwd)/ESP8266_RTOS_SDK

# activate virtual environment of python2.7
. $(pwd)/pyEnv/bin/activate
echo "Type 'deactivate' to leave virtual environment"

# choose the correct python binary (not the system python)
export PATH=$(pwd)/pyEnv/bin:\$PATH
EOF
fi
echo
echo "Setup completed successfully. Source setup_env with '. setup_env'..."
echo
